### ISSUE TITLE
SyntaxError: unexpected EOF while parsing

### ISSUE THREAD

**Issue by ghost** [DollarAkshay/WhatsApp-Chatbot#1]
As soon as i hit enter on terminal i get following error

Traceback (most recent call last):
  File "Whatsapp_Chat_Bot.py", line 30, in <module>
    input()
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

**Comment by DollarAkshay** [comment]
@chetanunadkat90 You have to scan the qrcode, wait for WhatsappWeb to load then select the person you wish to chat with and then press enter
