### ISSUE TITLE
NoSuchElementException

### ISSUE THREAD

**Issue by schnells** [DollarAkshay/WhatsApp-Chatbot#3]
Hello, was checking out your cool project, but got

<class 'selenium.common.exceptions.NoSuchElementException'> Whatsapp_Chat_Bot.py 47

What is this?

**Comment by LemuelKL** [comment]
I suspect the page elements names have changed.

**Comment by DollarAkshay** [comment]
Whatsapp Web has changed a bit, Ill work on a fix for this soon

**Comment by DollarAkshay** [comment]
Issue is now Fixed
